#!/bin/bash

finish() {
  f="${1}"
  [[ -z "${f}" || -z "${CYDIA}" ]] && return
  cydia=(${CYDIA})
  [[ ${cydia[1]} -eq 1 ]] || return
  echo "finish:${f}" >&${cydia[0]}
}

echo '[*] Removing beta profile configurations...'
rm -f '/var/mobile/Library/Preferences/com.apple.MobileAsset.plist'
rm -f '/var/Managed Preferences/mobile/com.apple.MobileAsset.plist'

echo '[*] Re-enabling OTA daemons...'
for f in mobile.softwareupdated OTATaskingAgent softwareupdateservicesd; do
  launchctl load -w /System/Library/LaunchDaemons/com.apple."$f".plist 2>&1 | grep -v 'service already loaded' >&2
done

echo '[*] Reverting changes made by unc0ver...'
if mount | grep -q /private/var/MobileSoftwareUpdate/mnt1/dev; then
  echo '[-] KernBypass is installed. Please uninstall it and reboot, then reinstall OTAEnabler.' >&2
  finish reboot
  exit 0
fi
files=(
  /var/MobileAsset/Assets/com_apple_MobileAsset_SoftwareUpdate
  /var/MobileAsset/Assets/com_apple_MobileAsset_SoftwareUpdateDocumentation
  /var/MobileAsset/AssetsV2/com_apple_MobileAsset_SoftwareUpdate
  /var/MobileAsset/AssetsV2/com_apple_MobileAsset_SoftwareUpdateDocumentation
  /var/MobileSoftwareUpdate/MobileAsset/AssetsV2
)
chflags -R noschg,nouchg,norestricted /var/MobileAsset /var/MobileSoftwareUpdate
for f in "${files[@]}"; do
  rm -rf "$f"
  install -m 755 -o root -g wheel -d "$f"
done

echo 'Done! Please do an ldrestart or userspace reboot for the changes to take effect.'
finish reboot
